/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID encmitcad17)
#  Generated on:      Fri Apr 10 18:12:47 2026
#  Design:            stopwatch
#  Command:           saveNetlist stopwatch.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr 10 2026 17:36:51 IST (Apr 10 2026 12:06:51 UTC)
// Verification Directory fv/stopwatch 
module RC_CG_MOD (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   TLATNTSCAX2 RC_CGIC_INST (.CK(ck_in),
	.E(enable),
	.ECK(ck_out),
	.SE(test));
endmodule

module RC_CG_MOD_1 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   // Internal wires
   wire FE_PHN48_n_120;

   DLY1X1 FE_PHC48_n_120 (.A(enable),
	.Y(FE_PHN48_n_120));
   TLATNTSCAX2 RC_CGIC_INST (.CK(ck_in),
	.E(FE_PHN48_n_120),
	.ECK(ck_out),
	.SE(test));
endmodule

module RC_CG_MOD_2 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   TLATNTSCAX2 RC_CGIC_INST (.CK(ck_in),
	.E(enable),
	.ECK(ck_out),
	.SE(test));
endmodule

module RC_CG_MOD_3 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   TLATNTSCAX2 RC_CGIC_INST (.CK(ck_in),
	.E(enable),
	.ECK(ck_out),
	.SE(test));
endmodule

module RC_CG_MOD_4 (
	enable, 
	ck_in, 
	ck_out, 
	test);
   input enable;
   input ck_in;
   output ck_out;
   input test;

   TLATNTSCAX2 RC_CGIC_INST (.CK(ck_in),
	.E(enable),
	.ECK(ck_out),
	.SE(test));
endmodule

module stopwatch (
	clk, 
	rst_n, 
	start_btn, 
	stop_btn, 
	lap_btn, 
	mins, 
	secs, 
	msecs, 
	lap_mins, 
	lap_secs, 
	lap_msecs);
   input clk;
   input rst_n;
   input start_btn;
   input stop_btn;
   input lap_btn;
   output [5:0] mins;
   output [5:0] secs;
   output [9:0] msecs;
   output [5:0] lap_mins;
   output [5:0] lap_secs;
   output [9:0] lap_msecs;

   // Internal wires
   wire FE_PHN61_mins_2;
   wire FE_PHN60_mins_5;
   wire FE_PHN59_secs_3;
   wire FE_PHN58_msecs_8;
   wire FE_PHN57_msecs_7;
   wire FE_PHN56_mins_4;
   wire FE_PHN55_secs_2;
   wire FE_PHN54_msecs_5;
   wire FE_PHN53_msecs_3;
   wire FE_PHN52_msecs_6;
   wire FE_PHN51_msecs_9;
   wire FE_PHN50_msecs_4;
   wire FE_PHN49_mins_1;
   wire FE_PHN47_inc_add_38_30_n_0;
   wire FE_PHN46_n_2;
   wire FE_PHN45_clkdiv_0;
   wire FE_PHN44_running;
   wire FE_PHN43_mins_0;
   wire FE_PHN42_lap_prev;
   wire FE_PHN41_msecs_1;
   wire FE_PHN40_n_1;
   wire FE_PHN39_n_4;
   wire FE_PHN38_secs_5;
   wire FE_PHN37_secs_4;
   wire FE_PHN36_msecs_0;
   wire FE_PHN35_mins_3;
   wire FE_PHN34_secs_1;
   wire FE_PHN33_msecs_2;
   wire FE_PHN32_secs_0;
   wire FE_PHN15_rst_n;
   wire [16:0] clkdiv;
   wire inc_add_38_30_n_0;
   wire inc_add_38_30_n_1;
   wire inc_add_38_30_n_2;
   wire inc_add_38_30_n_3;
   wire inc_add_38_30_n_5;
   wire inc_add_38_30_n_6;
   wire inc_add_38_30_n_7;
   wire inc_add_38_30_n_8;
   wire inc_add_38_30_n_9;
   wire inc_add_38_30_n_11;
   wire inc_add_38_30_n_12;
   wire inc_add_38_30_n_13;
   wire inc_add_38_30_n_15;
   wire inc_add_38_30_n_16;
   wire inc_add_38_30_n_17;
   wire inc_add_38_30_n_18;
   wire inc_add_38_30_n_21;
   wire inc_add_38_30_n_22;
   wire inc_add_38_30_n_23;
   wire inc_add_38_30_n_26;
   wire inc_add_38_30_n_27;
   wire inc_add_38_30_n_28;
   wire inc_add_38_30_n_32;
   wire inc_add_38_30_n_33;
   wire inc_add_38_30_n_36;
   wire inc_add_38_30_n_38;
   wire inc_add_38_30_n_40;
   wire inc_add_38_30_n_42;
   wire lap_prev;
   wire ms_tick;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_125;
   wire n_127;
   wire rc_gclk;
   wire rc_gclk_779;
   wire rc_gclk_781;
   wire rc_gclk_783;
   wire rc_gclk_785;
   wire running;

   DLY1X1 FE_PHC61_mins_2 (.A(mins[2]),
	.Y(FE_PHN61_mins_2));
   CLKBUFX3 FE_PHC60_mins_5 (.A(mins[5]),
	.Y(FE_PHN60_mins_5));
   CLKBUFX2 FE_PHC59_secs_3 (.A(secs[3]),
	.Y(FE_PHN59_secs_3));
   CLKBUFX2 FE_PHC58_msecs_8 (.A(msecs[8]),
	.Y(FE_PHN58_msecs_8));
   CLKBUFX2 FE_PHC57_msecs_7 (.A(msecs[7]),
	.Y(FE_PHN57_msecs_7));
   CLKBUFX2 FE_PHC56_mins_4 (.A(mins[4]),
	.Y(FE_PHN56_mins_4));
   CLKBUFX2 FE_PHC55_secs_2 (.A(secs[2]),
	.Y(FE_PHN55_secs_2));
   CLKBUFX2 FE_PHC54_msecs_5 (.A(msecs[5]),
	.Y(FE_PHN54_msecs_5));
   CLKBUFX2 FE_PHC53_msecs_3 (.A(msecs[3]),
	.Y(FE_PHN53_msecs_3));
   CLKBUFX2 FE_PHC52_msecs_6 (.A(msecs[6]),
	.Y(FE_PHN52_msecs_6));
   CLKBUFX2 FE_PHC51_msecs_9 (.A(msecs[9]),
	.Y(FE_PHN51_msecs_9));
   CLKBUFX2 FE_PHC50_msecs_4 (.A(msecs[4]),
	.Y(FE_PHN50_msecs_4));
   CLKBUFX2 FE_PHC49_mins_1 (.A(mins[1]),
	.Y(FE_PHN49_mins_1));
   CLKBUFX2 FE_PHC47_inc_add_38_30_n_0 (.A(inc_add_38_30_n_0),
	.Y(FE_PHN47_inc_add_38_30_n_0));
   CLKBUFX2 FE_PHC46_n_2 (.A(n_2),
	.Y(FE_PHN46_n_2));
   CLKBUFX2 FE_PHC45_clkdiv_0 (.A(clkdiv[0]),
	.Y(FE_PHN45_clkdiv_0));
   CLKBUFX6 FE_PHC44_running (.A(running),
	.Y(FE_PHN44_running));
   DLY1X1 FE_PHC43_mins_0 (.A(mins[0]),
	.Y(FE_PHN43_mins_0));
   CLKBUFX3 FE_PHC42_lap_prev (.A(lap_prev),
	.Y(FE_PHN42_lap_prev));
   DLY1X1 FE_PHC41_msecs_1 (.A(msecs[1]),
	.Y(FE_PHN41_msecs_1));
   CLKBUFX2 FE_PHC40_n_1 (.A(n_1),
	.Y(FE_PHN40_n_1));
   CLKBUFX2 FE_PHC39_n_4 (.A(n_4),
	.Y(FE_PHN39_n_4));
   CLKBUFX2 FE_PHC38_secs_5 (.A(secs[5]),
	.Y(FE_PHN38_secs_5));
   CLKBUFX2 FE_PHC37_secs_4 (.A(secs[4]),
	.Y(FE_PHN37_secs_4));
   CLKBUFX2 FE_PHC36_msecs_0 (.A(msecs[0]),
	.Y(FE_PHN36_msecs_0));
   CLKBUFX2 FE_PHC35_mins_3 (.A(mins[3]),
	.Y(FE_PHN35_mins_3));
   CLKBUFX3 FE_PHC34_secs_1 (.A(secs[1]),
	.Y(FE_PHN34_secs_1));
   CLKBUFX2 FE_PHC33_msecs_2 (.A(msecs[2]),
	.Y(FE_PHN33_msecs_2));
   CLKBUFX2 FE_PHC32_secs_0 (.A(secs[0]),
	.Y(FE_PHN32_secs_0));
   CLKBUFX3 FE_PHC15_rst_n (.A(rst_n),
	.Y(FE_PHN15_rst_n));
   RC_CG_MOD RC_CG_HIER_INST0 (.enable(n_125),
	.ck_in(clk),
	.ck_out(rc_gclk),
	.test(1'b0));
   RC_CG_MOD_1 RC_CG_HIER_INST1 (.enable(n_120),
	.ck_in(clk),
	.ck_out(rc_gclk_779),
	.test(1'b0));
   RC_CG_MOD_2 RC_CG_HIER_INST2 (.enable(ms_tick),
	.ck_in(clk),
	.ck_out(rc_gclk_781),
	.test(1'b0));
   RC_CG_MOD_3 RC_CG_HIER_INST3 (.enable(n_119),
	.ck_in(clk),
	.ck_out(rc_gclk_783),
	.test(1'b0));
   RC_CG_MOD_4 RC_CG_HIER_INST4 (.enable(n_118),
	.ck_in(clk),
	.ck_out(rc_gclk_785),
	.test(1'b0));
   NOR2XL g2233__2398 (.A(n_117),
	.B(n_94),
	.Y(n_119));
   INVXL g2234 (.A(n_94),
	.Y(n_118));
   NAND2XL g2235__5107 (.A(n_0),
	.B(ms_tick),
	.Y(n_94));
   NOR2BX1 g2236__6260 (.AN(running),
	.B(n_96),
	.Y(ms_tick));
   OR4XL g2237__4319 (.A(FE_PHN44_running),
	.B(clkdiv[1]),
	.C(clkdiv[2]),
	.D(n_92),
	.Y(n_120));
   NAND3X1 g2238__8428 (.A(clkdiv[0]),
	.B(clkdiv[1]),
	.C(n_93),
	.Y(n_96));
   AND4XL g2239__5526 (.A(clkdiv[4]),
	.B(clkdiv[3]),
	.C(clkdiv[2]),
	.D(n_91),
	.Y(n_93));
   OR4XL g2240__6783 (.A(clkdiv[3]),
	.B(clkdiv[4]),
	.C(clkdiv[0]),
	.D(n_90),
	.Y(n_92));
   NOR4X1 g2241__3680 (.A(clkdiv[5]),
	.B(clkdiv[12]),
	.C(clkdiv[13]),
	.D(n_88),
	.Y(n_91));
   OR4XL g2242__1617 (.A(clkdiv[9]),
	.B(clkdiv[10]),
	.C(clkdiv[11]),
	.D(n_87),
	.Y(n_90));
   NOR4BX1 g2244__2802 (.AN(msecs[5]),
	.B(msecs[3]),
	.C(msecs[4]),
	.D(n_86),
	.Y(n_0));
   NAND3BX1 g2245__1705 (.AN(clkdiv[14]),
	.B(clkdiv[15]),
	.C(n_85),
	.Y(n_88));
   OR4XL g2246__5122 (.A(clkdiv[12]),
	.B(clkdiv[13]),
	.C(clkdiv[15]),
	.D(n_84),
	.Y(n_87));
   NAND4XL g2247__8246 (.A(msecs[6]),
	.B(msecs[8]),
	.C(msecs[7]),
	.D(n_83),
	.Y(n_86));
   NOR4BX1 g2248__7098 (.AN(clkdiv[7]),
	.B(clkdiv[6]),
	.C(clkdiv[8]),
	.D(n_82),
	.Y(n_85));
   NAND4BXL g2249__6131 (.AN(secs[2]),
	.B(secs[4]),
	.C(secs[3]),
	.D(n_81),
	.Y(n_117));
   OR4XL g2250__1881 (.A(clkdiv[14]),
	.B(clkdiv[16]),
	.C(clkdiv[5]),
	.D(n_80),
	.Y(n_84));
   NOR2BX1 g2251__5115 (.AN(msecs[9]),
	.B(n_98),
	.Y(n_83));
   NAND4BXL g2252__7482 (.AN(clkdiv[11]),
	.B(clkdiv[10]),
	.C(clkdiv[9]),
	.D(clkdiv[16]),
	.Y(n_82));
   NOR2BXL g2253__4733 (.AN(lap_btn),
	.B(FE_PHN42_lap_prev),
	.Y(n_125));
   NOR2BXL g2254__6161 (.AN(secs[5]),
	.B(n_99),
	.Y(n_81));
   OR3XL g2255__9315 (.A(clkdiv[6]),
	.B(clkdiv[8]),
	.C(clkdiv[7]),
	.Y(n_80));
   NAND3X1 g2256__9945 (.A(msecs[0]),
	.B(msecs[1]),
	.C(msecs[2]),
	.Y(n_98));
   DFFRHQX2 \lap_msecs_reg[4]  (.CK(rc_gclk),
	.D(FE_PHN50_msecs_4),
	.Q(lap_msecs[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_mins_reg[5]  (.CK(rc_gclk),
	.D(FE_PHN60_mins_5),
	.Q(lap_mins[5]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_msecs_reg[6]  (.CK(rc_gclk),
	.D(FE_PHN52_msecs_6),
	.Q(lap_msecs[6]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_mins_reg[2]  (.CK(rc_gclk),
	.D(FE_PHN61_mins_2),
	.Q(lap_mins[2]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_msecs_reg[5]  (.CK(rc_gclk),
	.D(FE_PHN54_msecs_5),
	.Q(lap_msecs[5]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_secs_reg[3]  (.CK(rc_gclk),
	.D(FE_PHN59_secs_3),
	.Q(lap_secs[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_secs_reg[4]  (.CK(rc_gclk),
	.D(FE_PHN37_secs_4),
	.Q(lap_secs[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_msecs_reg[3]  (.CK(rc_gclk),
	.D(FE_PHN53_msecs_3),
	.Q(lap_msecs[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_secs_reg[2]  (.CK(rc_gclk),
	.D(FE_PHN55_secs_2),
	.Q(lap_secs[2]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_msecs_reg[2]  (.CK(rc_gclk),
	.D(FE_PHN33_msecs_2),
	.Q(lap_msecs[2]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_mins_reg[4]  (.CK(rc_gclk),
	.D(FE_PHN56_mins_4),
	.Q(lap_mins[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_msecs_reg[1]  (.CK(rc_gclk),
	.D(FE_PHN41_msecs_1),
	.Q(lap_msecs[1]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_mins_reg[1]  (.CK(rc_gclk),
	.D(FE_PHN49_mins_1),
	.Q(lap_mins[1]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_msecs_reg[0]  (.CK(rc_gclk),
	.D(FE_PHN36_msecs_0),
	.Q(lap_msecs[0]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 lap_prev_reg (.CK(clk),
	.D(lap_btn),
	.Q(lap_prev),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_mins_reg[0]  (.CK(rc_gclk),
	.D(FE_PHN43_mins_0),
	.Q(lap_mins[0]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_secs_reg[1]  (.CK(rc_gclk),
	.D(FE_PHN34_secs_1),
	.Q(lap_secs[1]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_mins_reg[3]  (.CK(rc_gclk),
	.D(FE_PHN35_mins_3),
	.Q(lap_mins[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_msecs_reg[9]  (.CK(rc_gclk),
	.D(FE_PHN51_msecs_9),
	.Q(lap_msecs[9]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_msecs_reg[8]  (.CK(rc_gclk),
	.D(FE_PHN58_msecs_8),
	.Q(lap_msecs[8]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_secs_reg[5]  (.CK(rc_gclk),
	.D(FE_PHN38_secs_5),
	.Q(lap_secs[5]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \lap_secs_reg[0]  (.CK(rc_gclk),
	.D(FE_PHN32_secs_0),
	.Q(lap_secs[0]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX2 \lap_msecs_reg[7]  (.CK(rc_gclk),
	.D(FE_PHN57_msecs_7),
	.Q(lap_msecs[7]),
	.RN(FE_PHN15_rst_n));
   NAND2XL g2280__2883 (.A(FE_PHN41_msecs_1),
	.B(FE_PHN36_msecs_0),
	.Y(n_97));
   NAND2XL g2281__2346 (.A(secs[1]),
	.B(secs[0]),
	.Y(n_99));
   DFFRHQX1 \clkdiv_reg[0]  (.CK(rc_gclk_779),
	.D(n_31),
	.Q(clkdiv[0]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[1]  (.CK(rc_gclk_779),
	.D(n_30),
	.Q(clkdiv[1]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[2]  (.CK(rc_gclk_779),
	.D(n_29),
	.Q(clkdiv[2]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[3]  (.CK(rc_gclk_779),
	.D(n_28),
	.Q(clkdiv[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[4]  (.CK(rc_gclk_779),
	.D(n_27),
	.Q(clkdiv[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[5]  (.CK(rc_gclk_779),
	.D(n_26),
	.Q(clkdiv[5]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[6]  (.CK(rc_gclk_779),
	.D(n_25),
	.Q(clkdiv[6]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[7]  (.CK(rc_gclk_779),
	.D(n_15),
	.Q(clkdiv[7]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[8]  (.CK(rc_gclk_779),
	.D(n_20),
	.Q(clkdiv[8]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[10]  (.CK(rc_gclk_779),
	.D(n_18),
	.Q(clkdiv[10]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[11]  (.CK(rc_gclk_779),
	.D(n_17),
	.Q(clkdiv[11]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[12]  (.CK(rc_gclk_779),
	.D(n_24),
	.Q(clkdiv[12]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[13]  (.CK(rc_gclk_779),
	.D(n_16),
	.Q(clkdiv[13]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[14]  (.CK(rc_gclk_779),
	.D(n_23),
	.Q(clkdiv[14]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[15]  (.CK(rc_gclk_779),
	.D(n_22),
	.Q(clkdiv[15]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \clkdiv_reg[16]  (.CK(rc_gclk_779),
	.D(n_21),
	.Q(clkdiv[16]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \mins_reg[1]  (.CK(rc_gclk_783),
	.D(n_14),
	.Q(mins[1]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \mins_reg[2]  (.CK(rc_gclk_783),
	.D(n_43),
	.Q(mins[2]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \mins_reg[3]  (.CK(rc_gclk_783),
	.D(n_56),
	.Q(mins[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \mins_reg[4]  (.CK(rc_gclk_783),
	.D(n_69),
	.Q(mins[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \mins_reg[5]  (.CK(rc_gclk_783),
	.D(n_71),
	.Q(mins[5]),
	.RN(FE_PHN15_rst_n));
   SDFFRHQX1 \msecs_reg[1]  (.CK(rc_gclk_781),
	.D(FE_PHN36_msecs_0),
	.Q(msecs[1]),
	.RN(FE_PHN15_rst_n),
	.SE(FE_PHN41_msecs_1),
	.SI(FE_PHN40_n_1));
   SDFFRHQX1 \msecs_reg[2]  (.CK(rc_gclk_781),
	.D(n_3),
	.Q(msecs[2]),
	.RN(FE_PHN15_rst_n),
	.SE(n_97),
	.SI(FE_PHN33_msecs_2));
   DFFRHQX1 \msecs_reg[3]  (.CK(rc_gclk_781),
	.D(n_33),
	.Q(msecs[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \msecs_reg[4]  (.CK(rc_gclk_781),
	.D(n_41),
	.Q(msecs[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \msecs_reg[5]  (.CK(rc_gclk_781),
	.D(n_55),
	.Q(msecs[5]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \msecs_reg[6]  (.CK(rc_gclk_781),
	.D(n_66),
	.Q(msecs[6]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \msecs_reg[7]  (.CK(rc_gclk_781),
	.D(n_72),
	.Q(msecs[7]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \msecs_reg[8]  (.CK(rc_gclk_781),
	.D(n_76),
	.Q(msecs[8]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \msecs_reg[9]  (.CK(rc_gclk_781),
	.D(n_79),
	.Q(msecs[9]),
	.RN(FE_PHN15_rst_n));
   SDFFRHQX1 running_reg (.CK(clk),
	.D(start_btn),
	.Q(running),
	.RN(FE_PHN15_rst_n),
	.SE(n_5),
	.SI(FE_PHN44_running));
   SDFFRHQX1 \secs_reg[1]  (.CK(rc_gclk_785),
	.D(FE_PHN32_secs_0),
	.Q(secs[1]),
	.RN(FE_PHN15_rst_n),
	.SE(FE_PHN34_secs_1),
	.SI(FE_PHN39_n_4));
   DFFRHQX1 \secs_reg[2]  (.CK(rc_gclk_785),
	.D(n_37),
	.Q(secs[2]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \secs_reg[3]  (.CK(rc_gclk_785),
	.D(n_44),
	.Q(secs[3]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \secs_reg[4]  (.CK(rc_gclk_785),
	.D(n_59),
	.Q(secs[4]),
	.RN(FE_PHN15_rst_n));
   DFFRHQX1 \secs_reg[5]  (.CK(rc_gclk_785),
	.D(n_64),
	.Q(secs[5]),
	.RN(FE_PHN15_rst_n));
   NOR2XL g1936__1666 (.A(n_0),
	.B(n_78),
	.Y(n_79));
   AOI21XL g1938__7410 (.A0(msecs[9]),
	.A1(n_73),
	.B0(n_77),
	.Y(n_78));
   NOR2XL g1939__6417 (.A(msecs[9]),
	.B(n_73),
	.Y(n_77));
   NOR2XL g1940__5477 (.A(n_0),
	.B(n_75),
	.Y(n_76));
   AOI21XL g1942__2398 (.A0(msecs[8]),
	.A1(n_67),
	.B0(n_74),
	.Y(n_75));
   NOR2XL g1943__5107 (.A(msecs[8]),
	.B(n_67),
	.Y(n_74));
   NOR2XL g1944__6260 (.A(n_70),
	.B(n_0),
	.Y(n_72));
   NAND2BX1 g1945__4319 (.AN(n_67),
	.B(msecs[8]),
	.Y(n_73));
   NOR2BX1 g1949__8428 (.AN(n_42),
	.B(n_65),
	.Y(n_71));
   AOI21XL g1950__5526 (.A0(msecs[7]),
	.A1(n_57),
	.B0(n_68),
	.Y(n_70));
   NOR2BX1 g1951__6783 (.AN(n_42),
	.B(n_61),
	.Y(n_69));
   NOR2XL g1952__3680 (.A(msecs[7]),
	.B(n_57),
	.Y(n_68));
   NOR2XL g1954__1617 (.A(n_63),
	.B(n_0),
	.Y(n_66));
   AOI21X1 g1955__2802 (.A0(mins[4]),
	.A1(n_54),
	.B0(mins[5]),
	.Y(n_65));
   NAND2BX1 g1956__1705 (.AN(n_57),
	.B(msecs[7]),
	.Y(n_67));
   NOR2BX1 g1957__5122 (.AN(n_117),
	.B(n_62),
	.Y(n_64));
   AOI21XL g1961__8246 (.A0(msecs[6]),
	.A1(n_49),
	.B0(n_60),
	.Y(n_63));
   AOI21X1 g1962__7098 (.A0(secs[5]),
	.A1(n_50),
	.B0(n_58),
	.Y(n_62));
   MXI2XL g1963__6131 (.A(n_54),
	.B(n_47),
	.S0(mins[4]),
	.Y(n_61));
   NOR2XL g1964__1881 (.A(msecs[6]),
	.B(n_49),
	.Y(n_60));
   NOR2BX1 g1965__5115 (.AN(n_117),
	.B(n_52),
	.Y(n_59));
   NOR2XL g1966__7482 (.A(secs[5]),
	.B(n_50),
	.Y(n_58));
   NOR2BX1 g1967__4733 (.AN(n_42),
	.B(n_51),
	.Y(n_56));
   NOR2XL g1968__6161 (.A(n_53),
	.B(n_0),
	.Y(n_55));
   NAND2BX1 g1969__9315 (.AN(n_49),
	.B(msecs[6]),
	.Y(n_57));
   INVX1 g1970 (.A(n_47),
	.Y(n_54));
   AOI21XL g1973__9945 (.A0(msecs[5]),
	.A1(n_38),
	.B0(n_48),
	.Y(n_53));
   AOI21X1 g1974__2883 (.A0(secs[4]),
	.A1(n_36),
	.B0(n_45),
	.Y(n_52));
   AOI21X1 g1975__2346 (.A0(mins[3]),
	.A1(n_35),
	.B0(n_46),
	.Y(n_51));
   NOR2XL g1976__1666 (.A(msecs[5]),
	.B(n_38),
	.Y(n_48));
   NAND2BX1 g1977__7410 (.AN(n_36),
	.B(secs[4]),
	.Y(n_50));
   NAND2BX1 g1979__6417 (.AN(n_38),
	.B(msecs[5]),
	.Y(n_49));
   NOR2XL g1980__5477 (.A(mins[3]),
	.B(n_35),
	.Y(n_46));
   NOR2XL g1981__2398 (.A(secs[4]),
	.B(n_36),
	.Y(n_45));
   AND2XL g1982__5107 (.A(n_40),
	.B(n_117),
	.Y(n_44));
   NOR2BX1 g1983__6260 (.AN(n_42),
	.B(n_39),
	.Y(n_43));
   NAND2BX1 g1984__4319 (.AN(n_35),
	.B(mins[3]),
	.Y(n_47));
   NAND4XL g1985__8428 (.A(mins[4]),
	.B(mins[5]),
	.C(mins[3]),
	.D(n_32),
	.Y(n_42));
   OA21XL g1988__5526 (.A0(msecs[4]),
	.A1(n_9),
	.B0(n_38),
	.Y(n_41));
   OAI21X1 g1989__6783 (.A0(secs[3]),
	.A1(n_8),
	.B0(n_34),
	.Y(n_40));
   MXI2XL g1990__3680 (.A(n_32),
	.B(n_7),
	.S0(mins[2]),
	.Y(n_39));
   NOR2BXL g1991__1617 (.AN(n_117),
	.B(n_12),
	.Y(n_37));
   NAND2XL g1994__2802 (.A(msecs[4]),
	.B(n_9),
	.Y(n_38));
   NAND2XL g1995__1705 (.A(secs[3]),
	.B(n_8),
	.Y(n_34));
   NOR2XL g1996__5122 (.A(n_13),
	.B(n_0),
	.Y(n_33));
   NAND2BX1 g1997__8246 (.AN(n_8),
	.B(secs[3]),
	.Y(n_36));
   NAND2XL g1998__7098 (.A(mins[2]),
	.B(n_32),
	.Y(n_35));
   INVX1 g1999 (.A(n_7),
	.Y(n_32));
   NOR2XL g2020__6131 (.A(FE_PHN45_clkdiv_0),
	.B(n_11),
	.Y(n_31));
   NOR2BXL g2021__1881 (.AN(n_100),
	.B(n_11),
	.Y(n_30));
   NOR2BXL g2022__5115 (.AN(n_101),
	.B(n_11),
	.Y(n_29));
   NOR2BXL g2023__7482 (.AN(n_102),
	.B(n_11),
	.Y(n_28));
   NOR2BXL g2024__4733 (.AN(n_103),
	.B(n_11),
	.Y(n_27));
   NOR2BXL g2025__6161 (.AN(n_104),
	.B(n_11),
	.Y(n_26));
   NOR2BXL g2026__9315 (.AN(n_105),
	.B(n_11),
	.Y(n_25));
   NOR2BXL g2027__9945 (.AN(n_111),
	.B(n_11),
	.Y(n_24));
   NOR2BXL g2028__2883 (.AN(n_113),
	.B(n_11),
	.Y(n_23));
   NOR2BXL g2029__2346 (.AN(n_114),
	.B(n_11),
	.Y(n_22));
   NOR2BXL g2030__1666 (.AN(n_115),
	.B(n_11),
	.Y(n_21));
   NOR2BXL g2031__7410 (.AN(n_107),
	.B(n_11),
	.Y(n_20));
   NOR2BXL g2033__5477 (.AN(n_109),
	.B(n_11),
	.Y(n_18));
   NOR2BXL g2034__2398 (.AN(n_110),
	.B(n_11),
	.Y(n_17));
   NOR2BXL g2035__5107 (.AN(n_112),
	.B(n_11),
	.Y(n_16));
   NOR2BXL g2036__6260 (.AN(n_106),
	.B(n_11),
	.Y(n_15));
   OA21XL g2037__4319 (.A0(mins[0]),
	.A1(mins[1]),
	.B0(n_7),
	.Y(n_14));
   AOI21XL g2038__8428 (.A0(msecs[3]),
	.A1(n_98),
	.B0(n_10),
	.Y(n_13));
   AOI21XL g2039__5526 (.A0(secs[2]),
	.A1(n_99),
	.B0(n_6),
	.Y(n_12));
   NOR2XL g2040__6783 (.A(msecs[3]),
	.B(n_98),
	.Y(n_10));
   NAND2XL g2044__3680 (.A(running),
	.B(n_96),
	.Y(n_11));
   NOR2XL g2045__1617 (.A(secs[2]),
	.B(n_99),
	.Y(n_6));
   NOR2BX1 g2046__2802 (.AN(msecs[3]),
	.B(n_98),
	.Y(n_9));
   NOR2XL g2047__1705 (.A(stop_btn),
	.B(start_btn),
	.Y(n_5));
   NAND2BX1 g2048__5122 (.AN(n_99),
	.B(secs[2]),
	.Y(n_8));
   NAND2XL g2049__8246 (.A(mins[0]),
	.B(mins[1]),
	.Y(n_7));
   INVX1 g2063 (.A(FE_PHN33_msecs_2),
	.Y(n_3));
   OAI21X1 inc_add_38_30_g249__7098 (.A0(clkdiv[11]),
	.A1(inc_add_38_30_n_40),
	.B0(inc_add_38_30_n_42),
	.Y(n_110));
   NAND2XL inc_add_38_30_g250__6131 (.A(clkdiv[11]),
	.B(inc_add_38_30_n_40),
	.Y(inc_add_38_30_n_42));
   OA21XL inc_add_38_30_g251__1881 (.A0(clkdiv[10]),
	.A1(inc_add_38_30_n_33),
	.B0(inc_add_38_30_n_40),
	.Y(n_109));
   NAND2XL inc_add_38_30_g252__5115 (.A(clkdiv[10]),
	.B(inc_add_38_30_n_33),
	.Y(inc_add_38_30_n_40));
   OAI21X1 inc_add_38_30_g253__7482 (.A0(clkdiv[15]),
	.A1(inc_add_38_30_n_26),
	.B0(inc_add_38_30_n_38),
	.Y(n_114));
   NAND2XL inc_add_38_30_g254__4733 (.A(clkdiv[15]),
	.B(inc_add_38_30_n_26),
	.Y(inc_add_38_30_n_38));
   OAI21X1 inc_add_38_30_g255__6161 (.A0(clkdiv[13]),
	.A1(inc_add_38_30_n_21),
	.B0(inc_add_38_30_n_36),
	.Y(n_112));
   NAND2XL inc_add_38_30_g256__9315 (.A(clkdiv[13]),
	.B(inc_add_38_30_n_21),
	.Y(inc_add_38_30_n_36));
   OAI21X1 inc_add_38_30_g258__2883 (.A0(clkdiv[7]),
	.A1(inc_add_38_30_n_16),
	.B0(inc_add_38_30_n_32),
	.Y(n_106));
   NOR2XL inc_add_38_30_g259__2346 (.A(inc_add_38_30_n_0),
	.B(inc_add_38_30_n_15),
	.Y(inc_add_38_30_n_33));
   NAND2XL inc_add_38_30_g260__1666 (.A(clkdiv[7]),
	.B(inc_add_38_30_n_16),
	.Y(inc_add_38_30_n_32));
   OA21XL inc_add_38_30_g261__7410 (.A0(clkdiv[14]),
	.A1(inc_add_38_30_n_22),
	.B0(inc_add_38_30_n_26),
	.Y(n_113));
   OAI21X1 inc_add_38_30_g262__6417 (.A0(clkdiv[16]),
	.A1(inc_add_38_30_n_18),
	.B0(inc_add_38_30_n_27),
	.Y(n_115));
   OAI21X1 inc_add_38_30_g263__5477 (.A0(clkdiv[5]),
	.A1(inc_add_38_30_n_12),
	.B0(inc_add_38_30_n_28),
	.Y(n_104));
   NAND2XL inc_add_38_30_g264__2398 (.A(clkdiv[5]),
	.B(inc_add_38_30_n_12),
	.Y(inc_add_38_30_n_28));
   NAND2XL inc_add_38_30_g265__5107 (.A(clkdiv[16]),
	.B(inc_add_38_30_n_18),
	.Y(inc_add_38_30_n_27));
   NAND2XL inc_add_38_30_g266__6260 (.A(clkdiv[14]),
	.B(inc_add_38_30_n_22),
	.Y(inc_add_38_30_n_26));
   OA21XL inc_add_38_30_g267__4319 (.A0(clkdiv[12]),
	.A1(inc_add_38_30_n_17),
	.B0(inc_add_38_30_n_21),
	.Y(n_111));
   OAI21X1 inc_add_38_30_g268__8428 (.A0(clkdiv[3]),
	.A1(inc_add_38_30_n_9),
	.B0(inc_add_38_30_n_23),
	.Y(n_102));
   NAND2XL inc_add_38_30_g269__5526 (.A(clkdiv[3]),
	.B(inc_add_38_30_n_9),
	.Y(inc_add_38_30_n_23));
   NOR2BX1 inc_add_38_30_g270__6783 (.AN(inc_add_38_30_n_17),
	.B(inc_add_38_30_n_3),
	.Y(inc_add_38_30_n_22));
   NAND2XL inc_add_38_30_g271__3680 (.A(clkdiv[12]),
	.B(inc_add_38_30_n_17),
	.Y(inc_add_38_30_n_21));
   OA21XL inc_add_38_30_g272__1617 (.A0(clkdiv[6]),
	.A1(inc_add_38_30_n_13),
	.B0(inc_add_38_30_n_16),
	.Y(n_105));
   OA21XL inc_add_38_30_g273__2802 (.A0(clkdiv[8]),
	.A1(inc_add_38_30_n_11),
	.B0(inc_add_38_30_n_15),
	.Y(n_107));
   NAND4XL inc_add_38_30_g274__1705 (.A(clkdiv[15]),
	.B(clkdiv[14]),
	.C(inc_add_38_30_n_8),
	.D(inc_add_38_30_n_11),
	.Y(inc_add_38_30_n_18));
   NOR2BX1 inc_add_38_30_g275__5122 (.AN(inc_add_38_30_n_11),
	.B(inc_add_38_30_n_5),
	.Y(inc_add_38_30_n_17));
   NAND2XL inc_add_38_30_g276__8246 (.A(clkdiv[6]),
	.B(inc_add_38_30_n_13),
	.Y(inc_add_38_30_n_16));
   NAND2XL inc_add_38_30_g277__7098 (.A(clkdiv[8]),
	.B(inc_add_38_30_n_11),
	.Y(inc_add_38_30_n_15));
   OA21XL inc_add_38_30_g278__6131 (.A0(clkdiv[4]),
	.A1(inc_add_38_30_n_6),
	.B0(inc_add_38_30_n_12),
	.Y(n_103));
   NOR2XL inc_add_38_30_g279__1881 (.A(inc_add_38_30_n_1),
	.B(inc_add_38_30_n_7),
	.Y(inc_add_38_30_n_13));
   NAND2XL inc_add_38_30_g280__5115 (.A(clkdiv[4]),
	.B(inc_add_38_30_n_6),
	.Y(inc_add_38_30_n_12));
   NOR4BBX1 inc_add_38_30_g281__7482 (.AN(clkdiv[7]),
	.BN(clkdiv[6]),
	.C(inc_add_38_30_n_1),
	.D(inc_add_38_30_n_7),
	.Y(inc_add_38_30_n_11));
   OA21XL inc_add_38_30_g282__4733 (.A0(clkdiv[2]),
	.A1(inc_add_38_30_n_2),
	.B0(inc_add_38_30_n_9),
	.Y(n_101));
   NAND2XL inc_add_38_30_g283__6161 (.A(clkdiv[2]),
	.B(inc_add_38_30_n_2),
	.Y(inc_add_38_30_n_9));
   NOR2XL inc_add_38_30_g284__9315 (.A(inc_add_38_30_n_3),
	.B(inc_add_38_30_n_5),
	.Y(inc_add_38_30_n_8));
   CLKINVX1 inc_add_38_30_g285 (.A(inc_add_38_30_n_7),
	.Y(inc_add_38_30_n_6));
   NAND3X1 inc_add_38_30_g286__9945 (.A(clkdiv[2]),
	.B(clkdiv[3]),
	.C(inc_add_38_30_n_2),
	.Y(inc_add_38_30_n_7));
   NAND4XL inc_add_38_30_g287__2883 (.A(clkdiv[9]),
	.B(clkdiv[11]),
	.C(clkdiv[8]),
	.D(clkdiv[10]),
	.Y(inc_add_38_30_n_5));
   AOI2BB1X1 inc_add_38_30_g288__2346 (.A0N(clkdiv[1]),
	.A1N(clkdiv[0]),
	.B0(inc_add_38_30_n_2),
	.Y(n_100));
   NAND2XL inc_add_38_30_g289__1666 (.A(clkdiv[13]),
	.B(clkdiv[12]),
	.Y(inc_add_38_30_n_3));
   AND2X1 inc_add_38_30_g290__7410 (.A(clkdiv[0]),
	.B(clkdiv[1]),
	.Y(inc_add_38_30_n_2));
   NAND2XL inc_add_38_30_g291__6417 (.A(clkdiv[5]),
	.B(clkdiv[4]),
	.Y(inc_add_38_30_n_1));
   DFFRX1 \secs_reg[0]  (.CK(rc_gclk_785),
	.D(FE_PHN39_n_4),
	.Q(secs[0]),
	.QN(n_4),
	.RN(FE_PHN15_rst_n));
   DFFRX4 \mins_reg[0]  (.CK(rc_gclk_783),
	.D(FE_PHN46_n_2),
	.Q(mins[0]),
	.QN(n_2),
	.RN(FE_PHN15_rst_n));
   DFFRX1 \msecs_reg[0]  (.CK(rc_gclk_781),
	.D(FE_PHN40_n_1),
	.Q(msecs[0]),
	.QN(n_1),
	.RN(FE_PHN15_rst_n));
   DFFRX1 \clkdiv_reg[9]  (.CK(rc_gclk_779),
	.D(n_127),
	.Q(clkdiv[9]),
	.QN(inc_add_38_30_n_0),
	.RN(FE_PHN15_rst_n));
   AOI211X1 g2 (.A0(FE_PHN47_inc_add_38_30_n_0),
	.A1(inc_add_38_30_n_15),
	.B0(inc_add_38_30_n_33),
	.C0(n_11),
	.Y(n_127));
endmodule

